; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; [common]
[platformio]
default_envs = motion

[env]
platform = espressif32 @ 6.9.0
lib_archive = no 		;temporary disabled to save time
lib_ldf_mode = deep+	;temporary disabled to save time
lib_deps = 
	fortyseveneffects/MIDI Library@ 5.0.2
	adafruit/Adafruit TinyUSB Library@ 3.1.0
	lathoub/AppleMIDI@ 3.3.0
	esphome/ESPAsyncWebServer-esphome@3.1.0 #issue with redifinitions from base webserver was solved in commit c4f25be and must be redone if the library gets updated.  
	esphome/AsyncTCP-esphome@2.1.1
	https://github.com/CNMAT/OSC.git#3.5.8
	bblanchon/ArduinoJson @ 7.2.0
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv
upload_speed = 921600
monitor_speed = 115200
build_unflags = -DARDUINO_USB_MODE=1
build_flags = 
	-DUSE_TINYUSB=1
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DASYNCWEBSERVER_REGEX
	-fpermissive
	'-DCFG_TUSB_CONFIG_FILE="${platformio.home_dir}/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include/arduino_tinyusb/include/tusb_config.h"'
	-DCORE_DEBUG_LEVEL=5
	-DASYNC_TCP_RUNNING_CORE=0
extra_scripts = 
  pre:scripts/copy_default_config.py
  pre:scripts/define-version.py

[base]
board = esp32-s3-devkitc-1
framework = arduino

[env:motion]
extends = base
build_unflags=
	${env.build_unflags}
build_flags=
  ${env.build_flags}
  -DPIPO_MOTION=1
lib_deps = 
	${env.lib_deps}
	https://github.com/isouriadakis/Arduino_ICM20948_DMP_Full-Function

[env:motiondebug]
extends = base
debug_tool = esp-builtin
build_type = debug
debug_init_break = break setup
debug_speed = 921600
build_unflags=
	${env.build_unflags}
build_flags=
  	; -DUSE_TINYUSB=1
	; -DARDUINO_USB_MODE=0
	; -DARDUINO_USB_CDC_ON_BOOT=1
	-DISABLE_USB_COMM
	-DASYNCWEBSERVER_REGEX
	-fpermissive
	'-DCFG_TUSB_CONFIG_FILE="${platformio.home_dir}/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include/arduino_tinyusb/include/tusb_config.h"'
	-DCORE_DEBUG_LEVEL=5
	-DASYNC_TCP_RUNNING_CORE=0
  -DPIPO_MOTION=1
lib_deps = 
	${env.lib_deps}
	https://github.com/isouriadakis/Arduino_ICM20948_DMP_Full-Function

[env:range]
extends = base
build_unflags=
	${env.build_unflags}
build_flags=
  ${env.build_flags}
  -DPIPO_RANGE=1
lib_deps =
	${env.lib_deps}
	stm32duino/STM32duino VL53L4CX@1.1.0

[env:analog]
extends = base
build_unflags=
	${env.build_unflags}
build_flags=
  ${env.build_flags}
  -DPIPO_ANALOG=1
lib_deps =
	${env.lib_deps}
	https://github.com/Dlloydev/ESP32-ESP32S2-AnalogWrite.git 
	;#5.0.2 ;temp library for testing purpuses

[env:native]
platform = native
build_flags = -std=gnu++11 
 -DUNIT_TEST=1
 -Itest/stubs/prefs 
 -fpermissive
build_type = test
test_framework = doctest
lib_deps =
    ArduinoFake