; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = motion

[env]
platform = espressif32 @ 6.9.0
lib_archive = no 		;temporary disabled to save time
lib_ldf_mode = deep+	;temporary disabled to save time
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv
upload_speed = 921600
monitor_speed = 115200
build_unflags = -DARDUINO_USB_MODE=1
build_flags = 
	-DUSE_TINYUSB=1
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DASYNCWEBSERVER_REGEX
	-fpermissive
	'-DCFG_TUSB_CONFIG_FILE="${platformio.home_dir}/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include/arduino_tinyusb/include/tusb_config.h"'
	-DCORE_DEBUG_LEVEL=5
	-DASYNC_TCP_RUNNING_CORE=0
extra_scripts = 
  pre:scripts/copy_default_config.py
  pre:scripts/define-version.py 

[base]
board = esp32-s3-devkitc-1
framework = arduino

[env:motion]
extends = base
build_flags=
  ${env.build_flags}
  -DPIPO_MOTION=1
  -DHW_REV=10
lib_extra_dirs = lib-variants/motion

[env:motion_rev1_1]
extends = env:motion
build_flags=
  ${env:motion.build_flags}
  -DHW_REV=11

[env:motiondebug] 
; best for dev => autoupload (no need to reset board) + minimal build time + serial debug info (But no USB Midi/HID)
; Note first time using this you have to reset the board, to have the usb mode toggled, then ok
extends = base
debug_tool = esp-builtin
build_type = debug
debug_init_break = tbreak setup
debug_speed = 921600
lib_archive = yes 		
lib_ldf_mode = chain	
build_unflags= ;needed empty to override env base
build_flags=
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DDISABLE_USB_COMM ; only disable midi usb setup for now.
	-DASYNCWEBSERVER_REGEX
	-fpermissive
	-DCORE_DEBUG_LEVEL=5
	-CONFIG_BT_NIMBLE_LOG_LEVEL=5
	-DASYNC_TCP_RUNNING_CORE=0
  	-DPIPO_MOTION=1
	-DPIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS ;not tested if improve anything
monitor_filters = esp32_exception_decoder ;not tested if improve anything
lib_extra_dirs = lib-variants/motion


[env:range]
extends = base
build_flags=
  ${env.build_flags}
  -DPIPO_RANGE=1
  -DHW_REV=10
lib_extra_dirs = lib-variants/range

[env:range_rev1_1]
extends = env:range
build_flags=
  ${env:range.build_flags}
  -DHW_REV=11

[env:analog]
extends = base
build_flags=
  ${env.build_flags}
  -DPIPO_ANALOG=1
  -DHW_REV=10
lib_extra_dirs = lib-variants/analog

[env:analog_rev2]
extends = env:analog
build_flags=
  ${env:analog.build_flags}
  -DHW_REV=20

[env:native]
platform = native
build_flags = -std=gnu++11 
 -DUNIT_TEST=1
 -Itest/stubs/prefs 
 -fpermissive
build_type = test
test_framework = doctest
lib_deps =
    ArduinoFake