; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_unflags = -DARDUINO_USB_MODE=1
build_flags = 
	-DUSE_TINYUSB=1
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DASYNCWEBSERVER_REGEX
	'-DCFG_TUSB_CONFIG_FILE="/Users/rup/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include/arduino_tinyusb/include/tusb_config.h"'
lib_archive = no
lib_ldf_mode = deep+
lib_deps = 
	wnatth3/WiFiManager @ 2.0.16-rc.2
	fortyseveneffects/MIDI Library@ 5.0.2
	adafruit/Adafruit TinyUSB Library@ 3.1.0
	lathoub/BLE-MIDI@ 2.2
	lathoub/AppleMIDI@ 3.3.0
	esphome/ESPAsyncWebServer-esphome@3.1.0
	esphome/AsyncTCP-esphome@2.1.1
	cnmat/OSC@^1.0.0
	sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.2.12
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv
upload_speed = 921600
