import type { Schema } from "./types";

export const schema: Schema = {
  name: {
    min: 4,
    max: 254,
  },
  motion: {
    accX: {
      label: "X-axis acceleration",
      cat: "Linear Acceleration",
      unit: "m/s²",
      min: -16,
      max: 16,
      step: 0.1,
      index: 3,
    },
    accY: {
      label: "Y-axis acceleration",
      cat: "Linear Acceleration",
      unit: "m/s²",
      min: -16,
      max: 16,
      step: 0.1,
      index: 4,
    },
    accZ: {
      label: "Z-axis acceleration",
      cat: "Linear Acceleration",
      unit: "m/s²",
      min: -16,
      max: 16,
      step: 0.1,
      index: 5,
    },
    pitch: {
      label: "Pitch",
      cat: "Rotations",
      unit: "°",
      min: -90,
      max: 90,
      step: 1,
      index: 1,
    },
    roll: {
      label: "Roll",
      cat: "Rotations",
      unit: "°",
      min: -180,
      max: 180,
      step: 1,
      index: 2,
    },
    yaw: {
      label: "Yaw",
      cat: "Rotations",
      unit: "°",
      min: -180,
      max: 180,
      step: 1,
      index: 0,
    },
    magX: {
      label: "X-axis MAG",
      cat: "Magnetometer",
      unit: "uT",
      min: -4900,
      max: 4900,
      step: 10,
      index: 6,
    },
    magY: {
      label: "Y-axis MAG",
      cat: "Magnetometer",
      unit: "uT",
      min: -4900,
      max: 4900,
      step: 10,
      index: 7,
    },
    magZ: {
      label: "Z-axis MAG",
      cat: "Magnetometer",
      unit: "uT",
      min: -4900,
      max: 4900,
      step: 10,
      index: 8,
    },
    gyroX: {
      label: "X-axis gyroscope",
      cat: "Angular Velocity",
      unit: "°/s",
      min: -2000,
      max: 2000,
      step: 1,
      index: 9,
    },
    gyroY: {
      label: "Y-axis gyroscope",
      cat: "Angular Velocity",
      unit: "°/s",
      min: -2000,
      max: 2000,
      step: 1,
      index: 10,
    },
    gyroZ: {
      label: "Z-axis gyroscope",
      cat: "Angular Velocity",
      unit: "°/s",
      min: -2000,
      max: 2000,
      step: 1,
      index: 11,
    },
  },
  range: {
    dist: {
      label: "Distance",
      cat: "dist",
      unit: "cm",
      min: 0,
      max: 300,
      step: 1,
      index: 0,
    },
  },
  analog: {
    A01: {
      label: "Analog 1",
      cat: "Voltage",
      unit: "",
      min: 0,
      max: 3.3,
      step: 0.1,
      index: 0,
    },
    A02: {
      label: "Analog 2",
      cat: "Voltage",
      unit: "",
      min: 0,
      max: 3.3,
      step: 0.1,
      index: 1,
    },
    A03: {
      label: "Analog 3",
      cat: "Voltage",
      unit: "V",
      min: 0,
      max: 3.1,
      step: 0.1,
      index: 2,
    },
    A04: {
      label: "Analog 4",
      cat: "Voltage",
      unit: "V",
      min: 0,
      max: 3.1,
      step: 0.1,
      index: 3,
    },
    A05: {
      label: "Analog 5",
      cat: "Voltage",
      unit: "V",
      min: 0,
      max: 3.1,
      step: 0.1,
      index: 4,
    },
    A06: {
      label: "Analog 6",
      cat: "Voltage",
      unit: "V",
      min: 0,
      max: 3.1,
      step: 0.1,
      index: 5,
    },
    A07: {
      label: "Analog 7",
      cat: "Voltage",
      unit: "",
      min: 0,
      max: 3.3,
      step: 0.1,
      index: 4,
    },
    A08: {
      label: "Analog 8",
      cat: "Voltage",
      unit: "",
      min: 0,
      max: 3.3,
      step: 0.1,
      index: 5,
    },
    T1: {
      label: "Touch 1",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 5000,
      step: 1,
      index: 6,
    },
    T2: {
      label: "Touch 2",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 5000,
      step: 1,
      index: 7,
    },
    T3: {
      label: "Touch 3",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 5000,
      step: 1,
      index: 8,
    },
    T4: {
      label: "Touch 4",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 5000,
      step: 1,
      index: 9,
    },
    T5: {
      label: "Touch 5",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 5000,
      step: 1,
      index: 10,
    },
    T6: {
      label: "Touch 6",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 5000,
      step: 1,
      index: 11,
    },
    T7: {
      label: "Touch 7",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 5000,
      step: 1,
      index: 12,
    },
    T8: {
      label: "Touch 8",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 5000,
      step: 1,
      index: 13,
    },
  },
  unknown: {
    "": { label: "", cat: "", unit: "", min: 0, max: 0, step: 1, index: 0 },
  },
};
