import type { Schema } from "./types";

export const schema: Schema = {
  motion: {
    accX: {
      label: "X-axis acceleration",
      cat: "Linear Acceleration",
      unit: "m/s²",
      min: -16,
      max: 16,
      step: 0.1,
    },
    accY: {
      label: "Y-axis acceleration",
      cat: "Linear Acceleration",
      unit: "m/s²",
      min: -16,
      max: 16,
      step: 0.1,
    },
    accZ: {
      label: "Z-axis acceleration",
      cat: "Linear Acceleration",
      unit: "m/s²",
      min: -16,
      max: 16,
      step: 0.1,
    },
    pitch: {
      label: "Pitch",
      cat: "Rotations",
      unit: "°",
      min: -90,
      max: 90,
      step: 1,
    },
    roll: {
      label: "Roll",
      cat: "Rotations",
      unit: "°",
      min: -180,
      max: 180,
      step: 1,
    },
    yaw: {
      label: "Yaw",
      cat: "Rotations",
      unit: "°",
      min: -180,
      max: 180,
      step: 1,
    },
  },
  range: {
    dist: {
      label: "Distance",
      cat: "",
      unit: "cm",
      min: 0,
      max: 400,
      step: 1,
    },
  },
  analog: {
    A1: {
      label: "Analog 1",
      cat: "Voltage",
      unit: "V",
      min: 0,
      max: 3.3,
      step: 0.1,
    },
    A2: {
      label: "Analog 2",
      cat: "Voltage",
      unit: "V",
      min: 0,
      max: 3.3,
      step: 0.1,
    },
    A3: {
      label: "Analog 3",
      cat: "Voltage",
      unit: "V",
      min: 0,
      max: 3.3,
      step: 0.1,
    },
    A4: {
      label: "Analog 4",
      cat: "Voltage",
      unit: "V",
      min: 0,
      max: 3.3,
      step: 0.1,
    },
    A5: {
      label: "Analog 5",
      cat: "Voltage",
      unit: "V",
      min: 0,
      max: 3.3,
      step: 0.1,
    },
    A6: {
      label: "Analog 6",
      cat: "Voltage",
      unit: "V",
      min: 0,
      max: 3.3,
      step: 0.1,
    },
    T1: {
      label: "Touch 1",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 200000,
      step: 1,
    },
    T2: {
      label: "Touch 2",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 200000,
      step: 1,
    },
    T3: {
      label: "Touch 3",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 200000,
      step: 1,
    },
    T4: {
      label: "Touch 4",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 200000,
      step: 1,
    },
    T5: {
      label: "Touch 5",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 200000,
      step: 1,
    },
    T6: {
      label: "Touch 6",
      cat: "Touch",
      unit: "-",
      min: 0,
      max: 200000,
      step: 1,
    },
  },
  unknown: { "": { label: "", cat: "", unit: "", min: 0, max: 0, step: 1 } },
};
