name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:

  platformio-build:
    name: PlatformIO Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [motion, range, analog, native]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache pip and PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run Unit Tests for native environment
        if: matrix.environment == 'native'
        run: pio test -e native

      - name: Build for ${{ matrix.environment }}
        if: matrix.environment != 'native'
        run: pio run -e ${{ matrix.environment }}

  svelte_build:
    name: Svelte Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: web-config/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('web-config/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Svelte Dependencies
        working-directory: web-config
        run: npm ci

      - name: Build Svelte App
        working-directory: web-config
        run: npm run build
